package com.imory.common.bean;

import java.util.Date;

public class PhoneCaptcha {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_captcha.id
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_captcha.phone
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_captcha.confirmCode
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    private String confirmCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_captcha.createTime
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_captcha.expireTime
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_captcha.id
     *
     * @return the value of phone_captcha.id
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_captcha.id
     *
     * @param id the value for phone_captcha.id
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_captcha.phone
     *
     * @return the value of phone_captcha.phone
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_captcha.phone
     *
     * @param phone the value for phone_captcha.phone
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_captcha.confirmCode
     *
     * @return the value of phone_captcha.confirmCode
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public String getConfirmCode() {
        return confirmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_captcha.confirmCode
     *
     * @param confirmCode the value for phone_captcha.confirmCode
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public void setConfirmCode(String confirmCode) {
        this.confirmCode = confirmCode == null ? null : confirmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_captcha.createTime
     *
     * @return the value of phone_captcha.createTime
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_captcha.createTime
     *
     * @param createTime the value for phone_captcha.createTime
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_captcha.expireTime
     *
     * @return the value of phone_captcha.expireTime
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_captcha.expireTime
     *
     * @param expireTime the value for phone_captcha.expireTime
     *
     * @mbggenerated Fri Sep 29 17:23:18 CST 2017
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
}