package com.imory.user.bean;

import java.util.Date;

public class UserBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.user_id
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.user_name
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.mobile
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.email
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.password
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.status
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.create_time
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.user_id
     *
     * @return the value of user_base.user_id
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.user_id
     *
     * @param user_id the value for user_base.user_id
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.user_name
     *
     * @return the value of user_base.user_name
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.user_name
     *
     * @param user_name the value for user_base.user_name
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.mobile
     *
     * @return the value of user_base.mobile
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.mobile
     *
     * @param mobile the value for user_base.mobile
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.email
     *
     * @return the value of user_base.email
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.email
     *
     * @param email the value for user_base.email
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.password
     *
     * @return the value of user_base.password
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.password
     *
     * @param password the value for user_base.password
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.status
     *
     * @return the value of user_base.status
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.status
     *
     * @param status the value for user_base.status
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.create_time
     *
     * @return the value of user_base.create_time
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.create_time
     *
     * @param create_time the value for user_base.create_time
     *
     * @mbggenerated Sat Sep 30 11:05:07 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}